ls:
  .dir: kebab-case
  .md: kebab-case | regex:[0-9A-Z\-]+
  .html: kebab-case
  .css: kebab-case
  student-bios:
    .md: regex:[a-z0-9A-Z\-]+

ignore:
  - .git
  - node_modules
  - .github
  - .vscode
  - admin
